version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER:-postgres
      - POSTGRES_PASSWORD:-postgres
      - POSTGRES_DB:-postgres
    env_file: .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 54432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80

  api:
    build:
      context: .
      args:
        - INSTALL_DEV=${INSTALL_DEV:-false}
    restart: unless-stopped
    depends_on:
      - db
    command: sh -c "poetry run alembic upgrade head &&
      poetry run uvicorn app.asgi:app --reload --reload-dir app --log-level debug --host 0.0.0.0 --port 8000"
    env_file: .env
    ports:
      - 3001:8000
    volumes:
      - '.:/app'

volumes:
  dbdata:
