version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB-postgres}
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT-5432}:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80

  api:
    build:
      context: .
      args:
        - INSTALL_DEV=${INSTALL_DEV:-false}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB-postgres}
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      POSTGRES_HOST: ${POSTGRES_HOST-db}
    depends_on:
      - db
    command: sh -c "poetry run alembic upgrade head &&
      poetry run uvicorn app.asgi:app --reload --reload-dir app --log-level debug --host 0.0.0.0 --port 8000"
    ports:
      - 3001:8000
    volumes:
      - '.:/app'

volumes:
  dbdata:
