"""Create Tables

Revision ID: a0d471234f42
Revises:
Create Date: 2021-07-03 16:36:31.057095

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a0d471234f42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
                    sa.Column('donor_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('donor_id')
                    )
    op.create_index(op.f('ix_donors_name'), 'donors', ['name'], unique=False)
    op.create_table('sponsors',
                    sa.Column('sponsor_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('logo_path', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('sponsor_id'),
                    sa.UniqueConstraint('logo_path'),
                    sa.UniqueConstraint('logo_path'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('career', sa.String(), nullable=True),
                    sa.Column('team', sa.String(), nullable=True),
                    sa.Column(
                        'profile_photo_path',
                        sa.String(),
                        nullable=True),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('profile_photo_path'),
                    sa.UniqueConstraint('profile_photo_path')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_team'), 'users', ['team'], unique=False)
    op.create_index(
        op.f('ix_users_username'),
        'users',
        ['username'],
        unique=True)
    op.create_table('announcements',
                    sa.Column('announcement_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('last_edit_at', sa.DateTime(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['author_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('announcement_id')
                    )
    op.create_index(
        op.f('ix_announcements_title'),
        'announcements',
        ['title'],
        unique=False)
    op.create_table('news',
                    sa.Column('new_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('subtitle', sa.String(), nullable=True),
                    sa.Column('reading_time', sa.Integer(), nullable=True),
                    sa.Column('subject', sa.String(), nullable=True),
                    sa.Column('content_dir', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('last_edit_at', sa.DateTime(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['author_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('new_id'),
                    sa.UniqueConstraint('content_dir'),
                    sa.UniqueConstraint('content_dir')
                    )
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_announcements_title'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_team'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sponsors')
    op.drop_index(op.f('ix_donors_name'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
