"""Remove unique constrain user picture

Revision ID: b075a76edba9
Revises: 9e80affcafdf
Create Date: 2021-09-12 20:54:27.050994

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'b075a76edba9'
down_revision = '9e80affcafdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_profile_photo_path_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'users_profile_photo_path_key',
        'users',
        ['profile_photo_path'])
    # ### end Alembic commands ###
