"""create tables

Revision ID: bfafc0702910
Revises:
Create Date: 2021-05-25 05:24:36.578211

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'bfafc0702910'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
                    sa.Column('donor_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('logo_path', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('donor_id'),
                    sa.UniqueConstraint('logo_path')
                    )
    op.create_index(op.f('ix_donors_donor_id'),
                    'donors', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donors_name'), 'donors', ['name'], unique=True)
    op.create_table('sponsors',
                    sa.Column('sponsor_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('logo_path', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('sponsor_id'),
                    sa.UniqueConstraint('logo_path'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_sponsors_sponsor_id'),
                    'sponsors', ['sponsor_id'], unique=False)
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=True),
                    sa.Column('profile_photo_path',
                              sa.String(), nullable=True),
                    sa.Column('career', sa.String(), nullable=True),
                    sa.Column('role', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('profile_photo_path')
                    )
    op.create_index(op.f('ix_users_career'), 'users', ['career'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users',
                    ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.create_table('contents',
                    sa.Column('content_id', sa.Integer(), nullable=False),
                    sa.Column('content_dir', sa.String(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('last_edit_at', sa.DateTime(), nullable=True),
                    sa.Column('type', sa.Enum('video', 'blog', 'news',
                                              'update', name='contentenum'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['author_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('content_id'),
                    sa.UniqueConstraint('content_dir')
                    )
    op.create_index(op.f('ix_contents_content_id'),
                    'contents', ['content_id'], unique=False)
    op.create_index(op.f('ix_contents_type'),
                    'contents', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_type'), table_name='contents')
    op.drop_index(op.f('ix_contents_content_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_career'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sponsors_sponsor_id'), table_name='sponsors')
    op.drop_table('sponsors')
    op.drop_index(op.f('ix_donors_name'), table_name='donors')
    op.drop_index(op.f('ix_donors_donor_id'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
